// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

namespace OpenRedding.Infrastructure.Persistence.Migrations.OpenRedding
{
    public partial class AddZoningTable : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "Zones",
                columns: table => new
                {
                    Id = table.Column<int>(nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    Zoning = table.Column<string>(nullable: true),
                    ZoningClass = table.Column<string>(nullable: false),
                    ZoningDescription = table.Column<string>(nullable: true),
                    ZoningDescriptionExtended = table.Column<string>(nullable: true),
                    ZoneId = table.Column<int>(nullable: false),
                    BaseDist = table.Column<string>(nullable: true),
                    OverlayDisctrict = table.Column<string>(nullable: true),
                    OverlayDistrictExtended = table.Column<string>(nullable: true),
                    ShapeLength = table.Column<double>(nullable: false),
                    ShapeArea = table.Column<double>(nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Zones", x => x.Id);
                });
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "Zones");
        }
    }
}
