// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

namespace OpenRedding.Infrastructure.Persistence.Migrations.OpenRedding
{
    public partial class InitialSalaryTableScaffold : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "Employees",
                columns: table => new
                {
                    EmployeeId = table.Column<int>(nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    EmployeeName = table.Column<string>(nullable: true),
                    JobTitle = table.Column<string>(nullable: true),
                    BasePay = table.Column<decimal>(type: "DECIMAL(9,2)", nullable: false),
                    OvertimePay = table.Column<decimal>(type: "DECIMAL(9,2)", nullable: false),
                    OtherPay = table.Column<decimal>(type: "DECIMAL(9,2)", nullable: false),
                    Benefits = table.Column<decimal>(type: "DECIMAL(9,2)", nullable: false),
                    TotalPay = table.Column<decimal>(type: "DECIMAL(9,2)", nullable: false),
                    PensionDebt = table.Column<decimal>(type: "DECIMAL(9,2)", nullable: true),
                    TotalPayWithBenefits = table.Column<decimal>(type: "DECIMAL(9,2)", nullable: false),
                    Year = table.Column<int>(nullable: false),
                    Notes = table.Column<string>(nullable: true),
                    EmployeeAgency = table.Column<string>(nullable: false),
                    EmployeeStatus = table.Column<string>(nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Employees", x => x.EmployeeId);
                });
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "Employees");
        }
    }
}
