// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

namespace OpenRedding.Infrastructure.Persistence.Migrations.OpenRedding
{
    public partial class AddReasonForUsePropertyToUserModel : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<string>(
                name: "ReasonForUse",
                table: "AspNetUsers",
                nullable: true);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "ReasonForUse",
                table: "AspNetUsers");
        }
    }
}
