# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
# Use the SDK version in global.json  
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    useGlobalJson: true

- script: dotnet build ./OpenRedding.sln --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'

# Run all unit and integration tests
- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: 'tests/**/*.csproj'
    testRunTitle: 'Run tests'

# Build the distribution files for the client
- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: true
    projects: 'source/OpenRedding.Client/OpenRedding.Client.csproj'
    arguments: '--no-build -o deploy'

# Copy the distribution files to the static web container
- task: AzureFileCopy@4
  inputs:
    SourcePath: '/deploy/wwwroot/'
    azureSubscription: 'Pay-As-You-Go(af2d9345-cd54-42f1-971c-e4926c8171b7)'
    Destination: 'AzureBlob'
    storage: 'openredding'
    ContainerName: '$web'