# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'

steps:
# Use the SDK version in global.json  
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    useGlobalJson: true

- script: dotnet build ./OpenRedding.sln --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'

# Run all unit and integration tests
- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: 'tests/**/*.csproj'
    testRunTitle: 'Run tests'

# Build the distribution files for the client
- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: 'source/OpenRedding.Client/OpenRedding.Client.csproj'
    arguments: '--output deploy'
    zipAfterPublish: false
    modifyOutputPath: true

 # Copy the distribution files to the static web container
- task: AzureFileCopy@4
  inputs:
    SourcePath: '$(Build.SourcesDirectory)/deploy/OpenRedding.Client/wwwroot'
    azureSubscription: '$env:AZURE_SUBSCRIPTION_ID'
    Destination: 'AzureBlob'
    storage: 'openredding'
    ContainerName: '$web'   

  env:
    AZURE_SUBSCRIPTION_ID: $(azureSubscriptionId)  
